// Generated by LiveScript 1.4.0
(function(){
  var exec, fsx, copy, mkdir, remove, write, readJSON, writeJSON, exists, mv, version, jsfiles, base_permissions, base_content_scripts, buildinfo_list, manifest_template, origdir, i$, len$, buildinfo, manifest, res$, k, v, short_name, baseurl, outdir, outfile, j$, len1$, file;
  exec = require('shelljs').exec;
  fsx = require('fs-extended');
  copy = fsx.copySync;
  mkdir = fsx.createDirSync;
  remove = fsx.deleteSync;
  write = fsx.createFileSync;
  readJSON = fsx.readJSONSync;
  writeJSON = fsx.writeJSONSync;
  exists = fsx.existsSync;
  mv = fsx.moveSync;
  version = '1.0';
  jsfiles = ['bower_components', 'abp_filter_parser.js', 'background.js', 'functions.js', 'contentscript.js', 'easylist_text.js'];
  base_permissions = ["http://*/*", "https://*/*"];
  base_content_scripts = [{
    "matches": ["http://*/*", "https://*/*"],
    "js": ["bower_components/jquery/dist/jquery.min.js", "functions.js", "baseurl.js", "contentscript.js"],
    "run_at": "document_start",
    "all_frames": true
  }];
  buildinfo_list = [
    {
      name: 'Edvertisements Local',
      short_name: 'edvertisementslocal',
      outdir: '.',
      baseurl: 'https://localhost:5001',
      permissions: base_permissions,
      content_scripts: base_content_scripts
    }, {
      name: 'Edvertisements',
      short_name: 'edvertisements',
      baseurl: 'https://edvertisements.herokuapp.com',
      permissions: base_permissions,
      content_scripts: base_content_scripts
    }
  ];
  manifest_template = readJSON('manifest.json');
  origdir = process.cwd();
  for (i$ = 0, len$ = buildinfo_list.length; i$ < len$; ++i$) {
    buildinfo = buildinfo_list[i$];
    res$ = {};
    for (k in manifest_template) {
      v = manifest_template[k];
      res$[k] = v;
    }
    manifest = res$;
    short_name = buildinfo.short_name, baseurl = buildinfo.baseurl, outdir = buildinfo.outdir;
    manifest.version = version;
    for (k in buildinfo) {
      v = buildinfo[k];
      if (['baseurl', 'outdir'].indexOf(k) !== -1) {
        continue;
      }
      manifest[k] = v;
    }
    if (outdir == null) {
      outdir = 'build_' + short_name;
    }
    outfile = short_name + '-' + version + '.zip';
    if (exists(outfile)) {
      remove(outfile);
    }
    if (outdir !== '.') {
      if (exists(outdir)) {
        remove(outdir);
      }
      mkdir(outdir);
      for (j$ = 0, len1$ = jsfiles.length; j$ < len1$; ++j$) {
        file = jsfiles[j$];
        copy(file, outdir + '/' + file, {
          clobber: true
        });
      }
    }
    process.chdir(outdir);
    writeJSON('manifest.json', manifest, '  ');
    write('baseurl.js', "baseurl = '" + baseurl + "';\n");
    exec("zip " + outfile + " *js manifest.json");
    mv(outfile, origdir + '/' + outfile);
    process.chdir(origdir);
  }
}).call(this);
