// Generated by LiveScript 1.4.0
(function(){
  var fs, easylist_text;
  require('es6-shim');
  fs = require('fs');
  easylist_text = fs.readFileSync('easylist_noelemhide.txt', 'utf-8');
  fs.writeFileSync('easylist_text.js', '(function(){\nvar out$ = typeof exports != \'undefined\' && exports || this;\nout$.easylist_text = ' + JSON.stringify(easylist_text, null, 2) + ';\n}).call(this);');
  /*
  url_to_check = 'http://static.tumblr.com/dhqhfum/WgAn39721/cfh_header_banner_v2.jpg'
  
  domain = '/static.tumblr.com'
  
  #console.log ABPFilterParser.matches(parsed_filter_data, url_to_check, {domain: domain, elementTypeMaskMap: ABPFilterParser.elementTypes.SCRIPT})
  console.log ABPFilterParser.matches(parsed_filter_data, url_to_check, {domain})
  */
}).call(this);
